services:
  app-service:
    # Use the image you built from your Dockerfile (using "docker build -t my-uv-app .")
    image: rag2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      
# Define the top-level named volume
volumes:
  # This makes the 'app-data' volume managed by Docker
  app-data:
